name: FoldBook
options:
  bundleIdPrefix: com.shimondeitel.origamilog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  FoldBook:
    type: application
    platform: iOS
    sources:
      - path: FoldBook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.origamilog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: FoldBook/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  FoldBookTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FoldBookTests
      - path: FoldBook.storekit
    dependencies:
      - target: FoldBook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.origamilog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  FoldBookUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FoldBookUITests
    dependencies:
      - target: FoldBook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.origamilog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  FoldBook:
    build:
      targets:
        FoldBook: all
        FoldBookTests: [test]
        FoldBookUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: FoldBook.storekit
    test:
      config: Debug
      storeKitConfiguration: FoldBook.storekit
      targets:
        - FoldBookTests
        - FoldBookUITests
    archive:
      config: Release
